# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposer',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposers', to='althingi.Issue'),
        ),
    ]
