# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-12 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0008_auto_20161212_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('l', 'lagafrumvarp'), ('a', '\xfeings\xe1lyktunartillaga'), ('m', 'fyrirspurn'), ('q', 'fyrirspurn til skriflegs svars'), ('s', 'sk\xfdrsla'), ('b', 'bei\xf0ni um sk\xfdrslu'), ('f', 'frestun \xe1 fundum Al\xfeingis'), ('n', '\xe1lit'), ('v', 'vantrauststillaga'), ('al', 'almennar stj\xf3rnm\xe1laumr\xe6\xf0ur'), ('av', '\xe1varp'), ('dr', 'drengskaparheit'), ('fh', 'framhaldsfundir Al\xfeingis'), ('ft', '\xf3undirb\xfainn fyrirspurnat\xedmi'), ('kb', 'ranns\xf3kn kj\xf6rbr\xe9fs'), ('ko', 'kosningar'), ('mi', 'minning'), ('ra', 'stefnur\xe6\xf0a fors\xe6tisr\xe1\xf0herra'), ('sr', 'sk\xfdrsla r\xe1\xf0herra'), ('st', 'st\xf6rf \xfeingsins'), ('s\xfe', 'munnleg sk\xfdrsla \xfeingmanns'), ('tk', 'tilkynningar forseta'), ('tr', 'tilkynning fr\xe1 r\xedkisstj\xf3rninni'), ('um', 's\xe9rst\xf6k umr\xe6\xf0a'), ('yf', 'yfirl\xfdsing forseta'), ('\xfei', '\xfeingsetning')], max_length=2),
        ),
    ]
