# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0016_auto_20170411_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField()),
                ('vote_casting_type', models.CharField(max_length=100)),
                ('specifics', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=50, null=True)),
                ('count_yes', models.IntegerField(null=True)),
                ('count_no', models.IntegerField(null=True)),
                ('count_abstain', models.IntegerField(null=True)),
                ('conclusion', models.CharField(max_length=100, null=True)),
                ('vote_casting_xml_id', models.IntegerField()),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_castings', to='althingi.Document')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_castings', to='althingi.Issue')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_castings', to='althingi.Session')),
                ('to_committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_castings', to='althingi.Committee')),
            ],
            options={
                'ordering': ['timing'],
            },
        ),
    ]
