# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0026_auto_20180214_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation_short', models.CharField(max_length=20)),
                ('abbreviation_long', models.CharField(max_length=30)),
                ('parliament_num_first', models.IntegerField()),
                ('parliament_num_last', models.IntegerField(null=True)),
                ('minister_xml_id', models.IntegerField(unique=True)),
                ('parliaments', models.ManyToManyField(related_name='ministers', to='althingi.Parliament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MinisterSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_in', models.DateTimeField()),
                ('timing_out', models.DateTimeField(null=True)),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minister_seats', to='althingi.Minister')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minister_seats', to='althingi.Parliament')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minister_seats', to='althingi.Party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minister_seats', to='althingi.Person')),
            ],
            options={
                'ordering': ['timing_in', 'timing_out'],
            },
        ),
        migrations.AlterField(
            model_name='issue',
            name='current_step',
            field=models.CharField(choices=[(b'distributed', 'Distributed'), (b'iteration-1-waiting', 'Awaiting 1st debate'), (b'iteration-1-current', 'Currently in 1st debate'), (b'iteration-1-finished', '1st debate concluded'), (b'committee-1-waiting', 'Sent to committee'), (b'committee-1-current', 'Currently in committee'), (b'committee-1-finished', 'Considered by committee'), (b'iteration-2-waiting', 'Awaiting 2nd debate'), (b'iteration-2-current', 'Currently in 2nd debate'), (b'iteration-2-finished', '2nd debate concluded'), (b'committee-2-waiting', 'Sent to committee (after 2nd debate)'), (b'committee-2-current', 'Currently in committee (after 2nd debate)'), (b'committee-2-finished', 'Considered by committee (after 2nd debate)'), (b'iteration-3-waiting', 'Awaiting 3rd debate'), (b'iteration-3-current', 'Currently in 3rd debate'), (b'iteration-3-finished', '3rd debate concluded'), (b'concluded', 'Issue concluded'), (b'distributed', 'Distributed'), (b'iteration-former-waiting', 'Awaiting former debate'), (b'iteration-former-current', 'Currently in former debate'), (b'iteration-former-finished', 'Former debate concluded'), (b'committee-former-waiting', 'Sent to committee'), (b'committee-former-current', 'Currently in committee'), (b'committee-former-finished', 'Considered by committee'), (b'iteration-latter-waiting', 'Awaiting latter debate'), (b'iteration-latter-current', 'Currently in latter debate'), (b'iteration-latter-finished', 'Latter debate concluded'), (b'concluded', 'Issue concluded'), (b'distributed', 'Distributed'), (b'answered', 'Answered'), (b'distributed', 'Distributed'), (b'voted-on', 'Voted on'), (b'report-delivered', 'Report delieverd'), (b'concluded', 'Concluded')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='parliament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='althingi.Parliament'),
        ),
    ]
