# Generated by Django 2.0.3 on 2018-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0033_auto_20180310_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='review_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='current_step',
            field=models.CharField(choices=[('distributed', 'Distributed'), ('iteration-1-waiting', 'Awaiting 1st debate'), ('iteration-1-current', 'Currently in 1st debate'), ('iteration-1-finished', '1st debate concluded'), ('committee-1-waiting', 'Sent to committee'), ('committee-1-current', 'Currently in committee'), ('committee-1-reviews-requested', 'Reviews requested'), ('committee-1-reviews-arrived', 'Reviews deadline expired'), ('committee-1-finished', 'Considered by committee'), ('iteration-2-waiting', 'Awaiting 2nd debate'), ('iteration-2-current', 'Currently in 2nd debate'), ('iteration-2-finished', '2nd debate concluded'), ('committee-2-waiting', 'Sent to committee (after 2nd debate)'), ('committee-2-current', 'Currently in committee (after 2nd debate)'), ('committee-2-finished', 'Considered by committee (after 2nd debate)'), ('iteration-3-waiting', 'Awaiting 3rd debate'), ('iteration-3-current', 'Currently in 3rd debate'), ('iteration-3-finished', '3rd debate concluded'), ('concluded', 'Issue concluded'), ('distributed', 'Distributed'), ('iteration-former-waiting', 'Awaiting former debate'), ('iteration-former-current', 'Currently in former debate'), ('iteration-former-finished', 'Former debate concluded'), ('committee-former-waiting', 'Sent to committee'), ('committee-former-current', 'Currently in committee'), ('committee-former-reviews-requested', 'Reviews requested'), ('committee-former-reviews-arrived', 'Reviews deadline expired'), ('committee-former-finished', 'Considered by committee'), ('iteration-latter-waiting', 'Awaiting latter debate'), ('iteration-latter-current', 'Currently in latter debate'), ('iteration-latter-finished', 'Latter debate concluded'), ('concluded', 'Issue concluded'), ('distributed', 'Distributed'), ('answered', 'Answered'), ('distributed', 'Distributed'), ('voted-on', 'Voted on'), ('report-delivered', 'Report delieverd'), ('concluded', 'Concluded')], max_length=40, null=True),
        ),
    ]
