# Generated by Django 2.0.3 on 2018-04-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0036_auto_20180410_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='final_vote_complete',
        ),
    ]
