# Generated by Django 2.0.3 on 2018-04-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0037_remove_issue_final_vote_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='to_committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='althingi.Committee'),
        ),
        migrations.AddField(
            model_name='issue',
            name='to_minister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='althingi.Minister'),
        ),
    ]
