# Generated by Django 2.0.4 on 2018-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0038_auto_20180420_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='president',
            field=models.BooleanField(default=False),
        ),
    ]
