# Generated by Django 2.2.5 on 2019-10-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0042_review_pending_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeagenda',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
