# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djalthingi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_access', models.BooleanField(default=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['friend__username'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_type', models.CharField(choices=[(b'document', 'Parliamentary Documents'), (b'review', 'Reviews')], max_length=10)),
                ('attention', models.CharField(choices=[(b'none', 'None'), (b'question', 'Question'), (b'exclamation', 'Exclamation')], default=b'none', max_length=20)),
                ('knowledge', models.IntegerField(choices=[(0, 'Unread'), (1, 'Briefly examined'), (2, 'Examined'), (3, 'Thoroughly examined')], default=0)),
                ('support', models.CharField(choices=[(b'undefined', 'Undefined'), (b'strongopposition', 'Strong Opposition'), (b'oppose', 'Oppose'), (b'neutral', 'Neutral'), (b'support', 'Support'), (b'strongsupport', 'Strong Support'), (b'other', 'Other')], default=b'undefined', max_length=20)),
                ('proposal', models.CharField(choices=[(b'none', 'None'), (b'minor', 'Minor'), (b'some', 'Some'), (b'major', 'Major')], default=b'none', max_length=20)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='djalthingi.Document')),
            ],
        ),
        migrations.CreateModel(
            name='DossierStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_useful_info', models.BooleanField(default=False)),
                ('document_attention_exclamation', models.IntegerField(default=0)),
                ('document_attention_question', models.IntegerField(default=0)),
                ('document_knowledge_0', models.IntegerField(default=0)),
                ('document_knowledge_1', models.IntegerField(default=0)),
                ('document_knowledge_2', models.IntegerField(default=0)),
                ('document_knowledge_3', models.IntegerField(default=0)),
                ('document_support_undefined', models.IntegerField(default=0)),
                ('document_support_strongopposition', models.IntegerField(default=0)),
                ('document_support_oppose', models.IntegerField(default=0)),
                ('document_support_neutral', models.IntegerField(default=0)),
                ('document_support_support', models.IntegerField(default=0)),
                ('document_support_strongsupport', models.IntegerField(default=0)),
                ('document_support_other', models.IntegerField(default=0)),
                ('document_proposal_minor', models.IntegerField(default=0)),
                ('document_proposal_some', models.IntegerField(default=0)),
                ('document_proposal_major', models.IntegerField(default=0)),
                ('document_count', models.IntegerField(default=0)),
                ('document_memo_count', models.IntegerField(default=0)),
                ('review_attention_exclamation', models.IntegerField(default=0)),
                ('review_attention_question', models.IntegerField(default=0)),
                ('review_knowledge_0', models.IntegerField(default=0)),
                ('review_knowledge_1', models.IntegerField(default=0)),
                ('review_knowledge_2', models.IntegerField(default=0)),
                ('review_knowledge_3', models.IntegerField(default=0)),
                ('review_support_undefined', models.IntegerField(default=0)),
                ('review_support_strongopposition', models.IntegerField(default=0)),
                ('review_support_oppose', models.IntegerField(default=0)),
                ('review_support_neutral', models.IntegerField(default=0)),
                ('review_support_support', models.IntegerField(default=0)),
                ('review_support_strongsupport', models.IntegerField(default=0)),
                ('review_support_other', models.IntegerField(default=0)),
                ('review_proposal_minor', models.IntegerField(default=0)),
                ('review_proposal_some', models.IntegerField(default=0)),
                ('review_proposal_major', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('review_memo_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IssueBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('order', models.IntegerField()),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='core.Dossier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='djalthingi.Person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('djalthingi.issue',),
        ),
        migrations.AddField(
            model_name='issuebookmark',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_bookmarks', to='djalthingi.Issue'),
        ),
        migrations.AddField(
            model_name='issuebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossierstatistic',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djalthingi.Issue'),
        ),
        migrations.AddField(
            model_name='dossierstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='djalthingi.Issue'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='djalthingi.Review'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='access',
            name='issues',
            field=models.ManyToManyField(to='core.Issue'),
        ),
        migrations.AddField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL),
        ),
    ]
