# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierstatistic",
            name="document_support_referral",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dossierstatistic",
            name="review_support_referral",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="support",
            field=models.CharField(
                choices=[
                    (b"undefined", "Undefined"),
                    (b"strongopposition", "Strong Opposition"),
                    (b"oppose", "Oppose"),
                    (b"neutral", "Neutral"),
                    (b"support", "Support"),
                    (b"strongsupport", "Strong Support"),
                    (b"referral", "Referral"),
                    (b"other", "Other"),
                ],
                default=b"undefined",
                max_length=20,
            ),
        ),
    ]
