# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20161218_2015"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="document",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="review",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="user",
        ),
        migrations.RemoveField(
            model_name="dossierstatistic",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="dossierstatistic",
            name="user",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="dossier",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="user",
        ),
        migrations.DeleteModel(
            name="Dossier",
        ),
        migrations.DeleteModel(
            name="DossierStatistic",
        ),
        migrations.DeleteModel(
            name="Memo",
        ),
    ]
