# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 13:43
from __future__ import unicode_literals

from django.db import migrations


def transfer_emails_to_usernames(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Seat = apps.get_model('djalthingi', 'Seat')

    for user in User.objects.select_related('userprofile__person').all():

        userprofile = user.userprofile
        person = userprofile.person

        if person is not None:
            initials = Seat.objects.filter(person=person).last().name_abbreviation
        else:
            initials = None

        user.username = user.email
        user.save()

        userprofile.initials = initials
        userprofile.save()


def reverse_initials(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')

    # We can't recover the usernames as they were before, but we can certainly
    # make more data unrecoverable!
    for userprofile in UserProfile.objects.all():
        userprofile.initials = None
        userprofile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_initials'),
    ]

    operations = [
        migrations.RunPython(transfer_emails_to_usernames, reverse_initials),
    ]
