# Generated by Django 2.0.3 on 2018-03-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0009_alter_user_last_name_max_length"),
        ("core", "0005_emails_as_usernames"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="access",
            options={
                "ordering": ["friend__userprofile__initials", "friend_group__name"]
            },
        ),
        migrations.AddField(
            model_name="access",
            name="friend_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_group_access",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="access",
            name="friend",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
