# Generated by Django 2.0.4 on 2019-01-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('althingi', '0040_auto_20181204_1544'),
        ('core', '0009_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='althingi.Category'),
        ),
    ]
