# Generated by Django 2.0.10 on 2019-01-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='setting_auto_bookmark',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(choices=[('party', 'Flokkar'), ('committee', 'Nefndir'), ('person', 'Þingmenn'), ('category', 'Efnisflokkar')], max_length=20),
        ),
    ]
