# Generated by Django 2.0.10 on 2019-03-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190117_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['sub_type']},
        ),
    ]
