# Generated by Django 2.2.6 on 2020-03-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0045_issue_committee_agenda_item_count"),
        ("core", "0016_userprofile_setting_hide_concluded_from_monitors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("djalthingi.document",),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("djalthingi.review",),
        ),
    ]
