# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation_short', models.CharField(max_length=20)),
                ('abbreviation_long', models.CharField(max_length=30)),
                ('committee_xml_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_start_planned', models.DateTimeField(null=True)),
                ('timing_start', models.DateTimeField(null=True)),
                ('timing_end', models.DateTimeField(null=True)),
                ('timing_text', models.CharField(max_length=200, null=True)),
                ('committee_agenda_xml_id', models.IntegerField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_agendas', to='djalthingi.Committee')),
            ],
            options={
                'ordering': ['timing_start_planned'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeAgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('committee_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_agenda_items', to='djalthingi.CommitteeAgenda')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_seat_type', models.CharField(choices=[('nefndarma\xf0ur', 'nefndarma\xf0ur'), ('varama\xf0ur', 'varama\xf0ur'), ('kj\xf6rinn varama\xf0ur', 'kj\xf6rinn varama\xf0ur'), ('forma\xf0ur', 'forma\xf0ur'), ('1. varaforma\xf0ur', '1. varaforma\xf0ur'), ('2. varaforma\xf0ur', '2. varaforma\xf0ur'), ('\xe1heyrnarfulltr\xfai', '\xe1heyrnarfulltr\xfai')], max_length=20)),
                ('order', models.IntegerField()),
                ('timing_in', models.DateTimeField()),
                ('timing_out', models.DateTimeField(null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_seats', to='djalthingi.Committee')),
            ],
            options={
                'ordering': ['timing_in', 'timing_out'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('abbreviation_short', models.CharField(max_length=20)),
                ('abbreviation_long', models.CharField(max_length=30, null=True)),
                ('parliament_num_first', models.IntegerField()),
                ('parliament_num_last', models.IntegerField(null=True)),
                ('constituency_xml_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.IntegerField()),
                ('doc_type', models.CharField(choices=[('bei\xf0ni um sk\xfdrslu', 'bei\xf0ni um sk\xfdrslu'), ('breytingartillaga', 'breytingartillaga'), ('frumvarp', 'frumvarp'), ('frumvarp eftir 2. umr\xe6\xf0u', 'frumvarp eftir 2. umr\xe6\xf0u'), ('frumvarp nefndar', 'frumvarp nefndar'), ('fsp. til munnl. svars', 'fyrirspurn til munnlegs svars'), ('fsp. til skrifl. svars', 'fyrirspurn til skriflegs svars'), ('l\xf6g (samhlj.)', 'l\xf6g (samhlj\xf3\xf0a)'), ('l\xf6g \xed heild', 'l\xf6g \xed heild'), ('n\xe1l. me\xf0 brtt.', 'nefndar\xe1lit me\xf0 breytingartill\xf6gu'), ('nefndar\xe1lit', 'nefndar\xe1lit'), ('sk\xfdrsla n. (frumskjal)', 'sk\xfdrsla nefndar (frumskjal)'), ('sk\xfdrsla rh. (frumskjal)', 'sk\xfdrsla r\xe1\xf0herra (frumskjal)'), ('stj\xf3rnarfrumvarp', 'stj\xf3rnarfrumvarp'), ('stj\xf3rnartillaga', 'stj\xf3rnartillaga'), ('svar', 'svar'), ('\xfe\xe1l. (samhlj.)', '\xfeings\xe1lyktunartillaga (samhlj\xf3\xf0a)'), ('\xfe\xe1l. \xed heild', '\xfeings\xe1lyktunartillaga \xed heild'), ('\xfe\xe1ltill.', '\xfeings\xe1lyktunartillaga'), ('\xfe\xe1ltill. n.', '\xfeings\xe1lyktunartillaga nefndar')], max_length=50)),
                ('time_published', models.DateTimeField()),
                ('is_main', models.BooleanField(default=False)),
                ('html_remote_path', models.CharField(max_length=500, null=True)),
                ('html_filename', models.CharField(max_length=50)),
                ('pdf_remote_path', models.CharField(max_length=500, null=True)),
                ('pdf_filename', models.CharField(max_length=50)),
                ('xhtml', models.TextField()),
            ],
            options={
                'ordering': ['doc_num'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_num', models.IntegerField()),
                ('issue_type', models.CharField(choices=[(b'l', b'lagafrumvarp'), (b'a', b'\xc3\xbeings\xc3\xa1lyktunartillaga'), (b'm', b'fyrirspurn'), (b'q', b'fyrirspurn til skriflegs svars'), (b's', b'sk\xc3\xbdrsla'), (b'b', b'bei\xc3\xb0ni um sk\xc3\xbdrslu')], max_length=1)),
                ('issue_group', models.CharField(choices=[(b'A', b'\xc3\xbeingm\xc3\xa1l me\xc3\xb0 \xc3\xbeingskj\xc3\xb6lum'), (b'B', b'\xc3\xbeingm\xc3\xa1l \xc3\xa1n \xc3\xbeingskjala')], default=b'A', max_length=1)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('final_vote_complete', models.BooleanField(default=False)),
                ('document_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['issue_num'],
            },
        ),
        migrations.CreateModel(
            name='IssueSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('change_description', models.TextField()),
                ('changes_to_law', models.TextField()),
                ('cost_and_revenue', models.TextField()),
                ('other_info', models.TextField()),
                ('review_description', models.TextField()),
                ('fate', models.TextField()),
                ('media_coverage', models.TextField()),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='djalthingi.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parliament_num', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation_short', models.CharField(max_length=20)),
                ('abbreviation_long', models.CharField(max_length=30)),
                ('parliament_num_first', models.IntegerField()),
                ('parliament_num_last', models.IntegerField(null=True)),
                ('party_xml_id', models.IntegerField()),
                ('parliaments', models.ManyToManyField(related_name='parties', to='djalthingi.Parliament')),
            ],
            options={
                'ordering': ['parliament_num_first'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('facebook_url', models.URLField(null=True)),
                ('twitter_url', models.URLField(null=True)),
                ('youtube_url', models.URLField(null=True)),
                ('blog_url', models.URLField(null=True)),
                ('website_url', models.URLField(null=True)),
                ('slug', models.CharField(max_length=100)),
                ('subslug', models.CharField(max_length=10, null=True)),
                ('person_xml_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proposer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('committee_partname', models.CharField(max_length=50, null=True)),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djalthingi.Committee')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposers', to='djalthingi.Document')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproposers', to='djalthingi.Proposer')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djalthingi.Person')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.IntegerField()),
                ('sender_name', models.CharField(max_length=200)),
                ('review_type', models.CharField(choices=[('aa', '\xe1\xe6tlun'), ('ab', 'afrit br\xe9fs'), ('ak', '\xe1lyktun'), ('al', '\xe1lit'), ('am', 'almennt'), ('as', '\xe1skorun'), ('at', 'athugasemd'), ('\xe1u', '\xe1bending til umfj\xf6llunar'), ('be', 'bei\xf0ni'), ('bk', 'b\xf3kun'), ('fr', 'frestun \xe1 ums\xf6gn'), ('fs', 'fyrirspurn'), ('ft', 'fr\xe9ttatilkynning'), ('fu', 'fundarger\xf0'), ('gg', 'greinarger\xf0'), ('it', '\xedtrekun'), ('ka', 'kostna\xf0ar\xe1\xe6tlun'), ('lf', 'lagt fram \xe1 fundi'), ('lr', 'lei\xf0r\xe9tting'), ('mb', 'minnisbla\xf0'), ('mm', 'm\xf3tm\xe6li'), ('mt', 'mat'), ('na', 'nefndar\xe1lit'), ('sa', 'sam\xfeykkt'), ('se', 'stu\xf0ningserindi'), ('sk', 'sk\xfdrsla'), ('su', 'sk\xfdrsla til umfj\xf6llunar'), ('tk', 'tilkynning'), ('tl', 'tillaga'), ('tm', 'tilm\xe6li'), ('ub', 'ums\xf6gn'), ('uk', 'ums\xf3kn'), ('up', 'uppl\xfdsingar'), ('vb', 'vi\xf0b\xf3tarums\xf6gn'), ('vs', 'vinnuskjal'), ('xx', 'x'), ('yf', 'yfirlit'), ('yg', '\xfdmis g\xf6gn'), ('ys', 'yfirl\xfdsing')], max_length=2)),
                ('date_arrived', models.DateField(null=True)),
                ('date_sent', models.DateField(null=True)),
                ('pdf_remote_path', models.CharField(max_length=500, null=True)),
                ('pdf_filename', models.CharField(max_length=50)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djalthingi.Committee')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='djalthingi.Issue')),
            ],
            options={
                'ordering': ['sender_name', 'date_arrived', 'log_num'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('\xfeingma\xf0ur', '\xfeingma\xf0ur'), ('varama\xf0ur', 'varama\xf0ur'), ('me\xf0 varamann', 'me\xf0 varamann')], max_length=20)),
                ('name_abbreviation', models.CharField(default=b'', max_length=15)),
                ('physical_seat_number', models.IntegerField(default=0, null=True)),
                ('timing_in', models.DateTimeField()),
                ('timing_out', models.DateTimeField(null=True)),
                ('constituency_mp_num', models.PositiveSmallIntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='djalthingi.Constituency')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='djalthingi.Parliament')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='djalthingi.Party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='djalthingi.Person')),
            ],
            options={
                'ordering': ['timing_in', 'timing_out'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_num', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('timing_start_planned', models.DateTimeField(null=True)),
                ('timing_start', models.DateTimeField(null=True)),
                ('timing_end', models.DateTimeField(null=True)),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='djalthingi.Parliament')),
            ],
            options={
                'ordering': ['session_num'],
            },
        ),
        migrations.CreateModel(
            name='SessionAgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('discussion_type', models.CharField(choices=[(b'*', ''), (b'0', ''), (b'1', '1. umr\xe6\xf0a'), (b'2', '2. umr\xe6\xf0a'), (b'3', '3. umr\xe6\xf0a'), (b'E', 'ein umr\xe6\xf0a'), (b'F', 'fyrri umr\xe6\xf0a'), (b'S', 's\xed\xf0ari umr\xe6\xf0a')], max_length=1)),
                ('discussion_continued', models.BooleanField(default=False)),
                ('comment_type', models.CharField(max_length=1, null=True)),
                ('comment_text', models.CharField(max_length=100, null=True)),
                ('comment_description', models.CharField(max_length=100, null=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_agenda_items', to='djalthingi.Issue')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_agenda_items', to='djalthingi.Session')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='parliament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djalthingi.Parliament'),
        ),
        migrations.AddField(
            model_name='issue',
            name='previous_issues',
            field=models.ManyToManyField(related_name='future_issues', to='djalthingi.Issue'),
        ),
        migrations.AddField(
            model_name='document',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='djalthingi.Issue'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='parliaments',
            field=models.ManyToManyField(related_name='constituencies', to='djalthingi.Parliament'),
        ),
        migrations.AddField(
            model_name='committeeseat',
            name='parliament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_seats', to='djalthingi.Parliament'),
        ),
        migrations.AddField(
            model_name='committeeseat',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_seats', to='djalthingi.Person'),
        ),
        migrations.AddField(
            model_name='committeeagendaitem',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_agenda_items', to='djalthingi.Issue'),
        ),
        migrations.AddField(
            model_name='committeeagenda',
            name='parliament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_agendas', to='djalthingi.Parliament'),
        ),
        migrations.AddField(
            model_name='committee',
            name='parliaments',
            field=models.ManyToManyField(related_name='committees', to='djalthingi.Parliament'),
        ),
    ]
