# Generated by Django 5.2.5 on 2025-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0002_auto_20200406_2126"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="html_content_raw",
            field=models.TextField(default=""),
        ),
    ]
