# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0002_proposer_issue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeeagenda",
            options={"ordering": ["timing_start_planned", "committee__name"]},
        ),
    ]
