# Generated by Django 5.2.5 on 2025-08-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0003_document_html_content_raw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="html_filename",
        ),
    ]
