# Generated by Django 5.2.5 on 2025-08-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0004_remove_document_html_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="is_law",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="is_resolution",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("álit nefndar um skýrslu", "álit nefndar um skýrslu"),
                    ("beiðni um skýrslu", "beiðni um skýrslu"),
                    ("breytingartillaga", "breytingartillaga"),
                    ("framhaldsnefndarálit", "framhaldsnefndarálit"),
                    ("frávísunartilllaga", "frávísunartilllaga"),
                    ("frestun funda", "frestun funda"),
                    ("frumvarp", "frumvarp"),
                    ("frhnál. með brtt.", "framhaldsnefndarálit með breytingartillögu"),
                    (
                        "frhnál. með frávt.",
                        "framhaldsnefndarálit með frávísunartillögu",
                    ),
                    ("frhnál. með rökst.", "framhaldsnefndarálit með rökstuðningi"),
                    ("frumvarp eftir 2. umræðu", "frumvarp eftir 2. umræðu"),
                    ("frumvarp nefndar", "frumvarp nefndar"),
                    ("frv. til. stjórnarsk.", "frumvarp til stjórnarskrár"),
                    ("fsp. til munnl. svars", "fyrirspurn til munnlegs svars"),
                    ("fsp. til skrifl. svars", "fyrirspurn til skriflegs svars"),
                    ("lög (m.áo.br.)", "lög (með áorðnum breytingum"),
                    ("lög (samhlj.)", "lög (samhljóða)"),
                    ("lög í heild", "lög í heild"),
                    ("nál. með brtt.", "nefndarálit með breytingartillögu"),
                    ("nál. með frávt.", "nefndarálit með frávísunartillögu"),
                    ("nál. með rökst.", "nefndarálit með rökstuðningi"),
                    ("nefndarálit", "nefndarálit"),
                    ("rökstudd dagskrá", "rökstudd dagskrá"),
                    ("skýrsla (skv. beiðni)", "skýrsla (samkvæmt beiðni)"),
                    ("skýrsla n.", "skýrsla nefndar"),
                    ("skýrsla n. (frumskjal)", "skýrsla nefndar (frumskjal)"),
                    ("skýrsla rh. (frumskjal)", "skýrsla ráðherra (frumskjal)"),
                    ("stjórnarfrumvarp", "stjórnarfrumvarp"),
                    ("stjórnartillaga", "stjórnartillaga"),
                    ("svar", "svar"),
                    ("vantraust", "vantraust"),
                    ("þál. (samhlj.)", "þingsályktun (samhljóða)"),
                    ("þál. í heild", "þingsályktun í heild"),
                    ("þáltill.", "þingsályktunartillaga"),
                    ("þáltill. n.", "þingsályktunartillaga nefndar"),
                ],
                max_length=50,
            ),
        ),
    ]
