# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0004_session_timing_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="sender_name_description",
            field=models.CharField(default=b"", max_length=200),
        ),
    ]
