# Generated by Django 5.2.5 on 2025-08-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0005_document_is_final_document_is_law_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="html_content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="law_identifier",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
