# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djalthingi', '0005_review_sender_name_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('aa', '\xe1\xe6tlun'), ('ab', 'afrit br\xe9fs'), ('ak', '\xe1lyktun'), ('al', '\xe1lit'), ('am', 'almennt'), ('as', '\xe1skorun'), ('at', 'athugasemd'), ('\xe1u', '\xe1bending til umfj\xf6llunar'), ('be', 'bei\xf0ni'), ('bk', 'b\xf3kun'), ('fr', 'frestun \xe1 ums\xf6gn'), ('fs', 'fyrirspurn'), ('ft', 'fr\xe9ttatilkynning'), ('fu', 'fundarger\xf0'), ('gg', 'greinarger\xf0'), ('it', '\xedtrekun'), ('ka', 'kostna\xf0ar\xe1\xe6tlun'), ('lf', 'lagt fram \xe1 fundi'), ('lr', 'lei\xf0r\xe9tting'), ('mb', 'minnisbla\xf0'), ('mm', 'm\xf3tm\xe6li'), ('mt', 'mat'), ('na', 'nefndar\xe1lit'), ('sa', 'sam\xfeykkt'), ('se', 'stu\xf0ningserindi'), ('sk', 'sk\xfdrsla'), ('su', 'sk\xfdrsla til umfj\xf6llunar'), ('tk', 'tilkynning'), ('tl', 'tillaga'), ('tm', 'tilm\xe6li'), ('ub', 'ums\xf6gn'), ('uk', 'ums\xf3kn'), ('up', 'uppl\xfdsingar'), ('vb', 'vi\xf0b\xf3tarums\xf6gn'), ('vi', 'vi\xf0auki'), ('vs', 'vinnuskjal'), ('xx', 'x'), ('yf', 'yfirlit'), ('yg', '\xfdmis g\xf6gn'), ('ys', 'yfirl\xfdsing')], max_length=2),
        ),
    ]
