# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-12 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djalthingi', '0006_auto_20161212_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[(b'l', b'lagafrumvarp'), (b'a', b'\xc3\xbeings\xc3\xa1lyktunartillaga'), (b'm', b'fyrirspurn'), (b'q', b'fyrirspurn til skriflegs svars'), (b's', b'sk\xc3\xbdrsla'), (b'b', b'bei\xc3\xb0ni um sk\xc3\xbdrslu'), (b'f', b'frestun \xc3\xa1 fundum Al\xc3\xbeingis'), (b'n', b'\xc3\xa1lit'), (b'v', b'vantrauststillaga')], max_length=1),
        ),
    ]
