# Generated by Django 5.2.5 on 2025-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0006_document_html_content_document_law_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="law_identifier",
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
