# Generated by Django 5.2.5 on 2025-09-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0007_alter_document_law_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="law_time_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
