# Generated by Django 5.2.6 on 2025-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0008_document_law_time_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="law_time_signed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="law_time_voted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
