# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djalthingi', '0009_auto_20161212_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djalthingi.Committee'),
        ),
    ]
