# Generated by Django 5.2.8 on 2025-11-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0009_document_law_time_signed_document_law_time_voted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minister",
            name="abbreviation_long",
            field=models.CharField(max_length=50),
        ),
    ]
