# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djalthingi', '0011_auto_20161212_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='time_published',
            field=models.DateTimeField(null=True),
        ),
    ]
