# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0015_auto_20161229_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="parliament_num_first",
            field=models.IntegerField(default=146),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="committee",
            name="parliament_num_last",
            field=models.IntegerField(null=True),
        ),
    ]
