# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0018_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    (
                        "\xe1lit nefndar um sk\xfdrslu",
                        b"\xc3\xa1lit nefndar um sk\xc3\xbdrslu",
                    ),
                    ("bei\xf0ni um sk\xfdrslu", "bei\xf0ni um sk\xfdrslu"),
                    ("breytingartillaga", "breytingartillaga"),
                    ("framhaldsnefndar\xe1lit", "framhaldsnefndar\xe1lit"),
                    ("fr\xe1v\xedsunartilllaga", "fr\xe1v\xedsunartilllaga"),
                    ("frestun funda", "frestun funda"),
                    ("frumvarp", "frumvarp"),
                    (
                        "frhn\xe1l. me\xf0 brtt.",
                        "framhaldsnefndar\xe1lit me\xf0 breytingartill\xf6gu",
                    ),
                    (
                        "frhn\xe1l. me\xf0 fr\xe1vt.",
                        "framhaldsnefndar\xe1lit me\xf0 fr\xe1v\xedsunartill\xf6gu",
                    ),
                    (
                        "frhn\xe1l. me\xf0 r\xf6kst.",
                        "framhaldsnefndar\xe1lit me\xf0 r\xf6kstu\xf0ningi",
                    ),
                    (
                        "frumvarp eftir 2. umr\xe6\xf0u",
                        "frumvarp eftir 2. umr\xe6\xf0u",
                    ),
                    ("frumvarp nefndar", "frumvarp nefndar"),
                    ("frv. til. stj\xf3rnarsk.", "frumvarp til stj\xf3rnarskr\xe1r"),
                    ("fsp. til munnl. svars", "fyrirspurn til munnlegs svars"),
                    ("fsp. til skrifl. svars", "fyrirspurn til skriflegs svars"),
                    ("l\xf6g (m.\xe1o.br.)", "l\xf6g (me\xf0 \xe1or\xf0num breytingum"),
                    ("l\xf6g (samhlj.)", "l\xf6g (samhlj\xf3\xf0a)"),
                    ("l\xf6g \xed heild", "l\xf6g \xed heild"),
                    (
                        "n\xe1l. me\xf0 brtt.",
                        "nefndar\xe1lit me\xf0 breytingartill\xf6gu",
                    ),
                    (
                        "n\xe1l. me\xf0 fr\xe1vt.",
                        "nefndar\xe1lit me\xf0 fr\xe1v\xedsunartill\xf6gu",
                    ),
                    (
                        "n\xe1l. me\xf0 r\xf6kst.",
                        "nefndar\xe1lit me\xf0 r\xf6kstu\xf0ningi",
                    ),
                    ("nefndar\xe1lit", "nefndar\xe1lit"),
                    ("r\xf6kstudd dagskr\xe1", "r\xf6kstudd dagskr\xe1"),
                    (
                        "sk\xfdrsla (skv. bei\xf0ni)",
                        "sk\xfdrsla (samkv\xe6mt bei\xf0ni)",
                    ),
                    ("sk\xfdrsla n.", "sk\xfdrsla nefndar"),
                    ("sk\xfdrsla n. (frumskjal)", "sk\xfdrsla nefndar (frumskjal)"),
                    (
                        "sk\xfdrsla rh. (frumskjal)",
                        "sk\xfdrsla r\xe1\xf0herra (frumskjal)",
                    ),
                    ("stj\xf3rnarfrumvarp", "stj\xf3rnarfrumvarp"),
                    ("stj\xf3rnartillaga", "stj\xf3rnartillaga"),
                    ("svar", "svar"),
                    ("vantraust", "vantraust"),
                    (
                        "\xfe\xe1l. (samhlj.)",
                        "\xfeings\xe1lyktunartillaga (samhlj\xf3\xf0a)",
                    ),
                    ("\xfe\xe1l. \xed heild", "\xfeings\xe1lyktunartillaga \xed heild"),
                    ("\xfe\xe1ltill.", "\xfeings\xe1lyktunartillaga"),
                    ("\xfe\xe1ltill. n.", "\xfeings\xe1lyktunartillaga nefndar"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote_response",
            field=models.CharField(
                choices=[
                    ("j\xe1", "j\xe1"),
                    ("nei", "nei"),
                    ("fjarverandi", "fjarverandi"),
                    ("bo\xf0a\xf0i fjarvist", "bo\xf0a\xf0i fjarvist"),
                    ("grei\xf0ir ekki atkv\xe6\xf0i", "grei\xf0ir ekki atkv\xe6\xf0i"),
                ],
                max_length=20,
            ),
        ),
    ]
