# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:45
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('djalthingi', '0023_parliament_last_full_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votecasting',
            old_name='vote_casting_type',
            new_name='vote_casting_type_text',
        ),
        migrations.AddField(
            model_name='votecasting',
            name='vote_casting_type',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
