# Generated by Django 2.0.3 on 2018-03-20 12:58

from django.db import migrations, models


def configure_standing_committees(apps, schema_editor):
    Committee = apps.get_model('djalthingi', 'Committee')

    NON_STANDING_COMMITTIES = (
        'forsætisnefnd',
        'Íslandsdeild Alþjóðaþingmannasambandsins',
        'Íslandsdeild Evrópuráðsþingsins',
        'Íslandsdeild NATO-þingsins',
        'Íslandsdeild Norðurlandaráðs',
        'Íslandsdeild Vestnorræna ráðsins',
        'Íslandsdeild Vestur-Evrópusambandsins',
        'Íslandsdeild þingmannanefnda EFTA og EES',
        'Íslandsdeild þingmannanefndar EFTA',
        'Íslandsdeild þingmannaráðstefnunnar um norðurskautsmál',
        'Íslandsdeild þings Öryggis- og samvinnustofnunar Evrópu',
        'kjörbréfanefnd',
        'sérnefnd um stjórnarskrármál',
        'sérnefnd um stjórnarskrármál (385. mál á 136. þingi)',
        'starfshópur utanríkismálanefndar um Evrópumál',
        'Þingmannanefnd Íslands og Evrópusambandsins af hálfu Alþingis',
        'þingmannanefnd til að fjalla um skýrslu rannsóknarnefndar Alþingis',
        'þingskapanefnd',
    )

    for committee in Committee.objects.all():
        committee.is_standing = committee.name not in NON_STANDING_COMMITTIES
        committee.save()


# Only here for migration reversability.
def dummy_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('djalthingi', '0034_auto_20180319_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_standing',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(configure_standing_committees, dummy_function)
    ]
