# Generated by Django 2.0.4 on 2018-12-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0039_speech_president"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="djalthingi.CategoryGroup",
            ),
        ),
    ]
