# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dossier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dossiers",
                to="djalthingi.Document",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dossiers",
                to="djalthingi.Review",
            ),
        ),
    ]
