# Generated by Django 2.2.6 on 2020-01-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0002_auto_20170530_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
