# Generated by Django 2.2.6 on 2020-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0003_dossier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='is_useful',
            field=models.BooleanField(default=False),
        ),
    ]
