# Generated by Django 2.2.6 on 2020-03-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0004_dossier_is_useful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierstatistic',
            name='document_memo_count',
        ),
        migrations.RemoveField(
            model_name='dossierstatistic',
            name='review_memo_count',
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
